{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyNK/MsuURpVkDmn1v1rfBx0"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["ローカル環境で作成したSARIMAXモデルです。\n","Google Colaboratoryの場合、pandas,numpyのインストール時にエラー出て再起動を求められますが、そのまま実行できます。"],"metadata":{"id":"4eFbEUINBJqa"}},{"cell_type":"code","source":["!pip install --force-reinstall pandas==1.5.3\n","!pip install --force-reinstall numpy==1.26.4"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"id":"ImIu1b6czLPK","executionInfo":{"status":"ok","timestamp":1726808433813,"user_tz":-540,"elapsed":45100,"user":{"displayName":"yuto “yuto2910” y","userId":"17489193892175419314"}},"outputId":"ce1160e3-4277-4ab2-96f5-1f85be302beb"},"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting pandas==1.5.3\n","  Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)\n","Collecting python-dateutil>=2.8.1 (from pandas==1.5.3)\n","  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)\n","Collecting pytz>=2020.1 (from pandas==1.5.3)\n","  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)\n","Collecting numpy>=1.21.0 (from pandas==1.5.3)\n","  Downloading numpy-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m60.9/60.9 kB\u001b[0m \u001b[31m573.7 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hCollecting six>=1.5 (from python-dateutil>=2.8.1->pandas==1.5.3)\n","  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)\n","Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m12.1/12.1 MB\u001b[0m \u001b[31m26.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading numpy-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m16.3/16.3 MB\u001b[0m \u001b[31m15.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m229.9/229.9 kB\u001b[0m \u001b[31m7.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hUsing cached pytz-2024.2-py2.py3-none-any.whl (508 kB)\n","Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)\n","Installing collected packages: pytz, six, numpy, python-dateutil, pandas\n","  Attempting uninstall: pytz\n","    Found existing installation: pytz 2024.2\n","    Uninstalling pytz-2024.2:\n","      Successfully uninstalled pytz-2024.2\n","  Attempting uninstall: six\n","    Found existing installation: six 1.16.0\n","    Uninstalling six-1.16.0:\n","      Successfully uninstalled six-1.16.0\n","  Attempting uninstall: numpy\n","    Found existing installation: numpy 1.26.4\n","    Uninstalling numpy-1.26.4:\n","      Successfully uninstalled numpy-1.26.4\n","  Attempting uninstall: python-dateutil\n","    Found existing installation: python-dateutil 2.8.2\n","    Uninstalling python-dateutil-2.8.2:\n","      Successfully uninstalled python-dateutil-2.8.2\n","  Attempting uninstall: pandas\n","    Found existing installation: pandas 2.1.4\n","    Uninstalling pandas-2.1.4:\n","      Successfully uninstalled pandas-2.1.4\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","cudf-cu12 24.4.1 requires numpy<2.0a0,>=1.23, but you have numpy 2.1.1 which is incompatible.\n","cudf-cu12 24.4.1 requires pandas<2.2.2dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.\n","cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.1.1 which is incompatible.\n","gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.1.1 which is incompatible.\n","google-colab 1.0.0 requires pandas==2.1.4, but you have pandas 1.5.3 which is incompatible.\n","ibis-framework 8.0.0 requires numpy<2,>=1, but you have numpy 2.1.1 which is incompatible.\n","mizani 0.11.4 requires pandas>=2.1.0, but you have pandas 1.5.3 which is incompatible.\n","numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.1.1 which is incompatible.\n","plotnine 0.13.6 requires pandas<3.0.0,>=2.1.0, but you have pandas 1.5.3 which is incompatible.\n","pytensor 2.25.4 requires numpy<2,>=1.17.0, but you have numpy 2.1.1 which is incompatible.\n","rmm-cu12 24.4.0 requires numpy<2.0a0,>=1.23, but you have numpy 2.1.1 which is incompatible.\n","scikit-learn 1.3.2 requires numpy<2.0,>=1.17.3, but you have numpy 2.1.1 which is incompatible.\n","tensorflow 2.17.0 requires numpy<2.0.0,>=1.23.5; python_version <= \"3.11\", but you have numpy 2.1.1 which is incompatible.\n","thinc 8.2.5 requires numpy<2.0.0,>=1.19.0; python_version >= \"3.9\", but you have numpy 2.1.1 which is incompatible.\n","xarray 2024.9.0 requires pandas>=2.1, but you have pandas 1.5.3 which is incompatible.\u001b[0m\u001b[31m\n","\u001b[0mSuccessfully installed numpy-2.1.1 pandas-1.5.3 python-dateutil-2.9.0.post0 pytz-2024.2 six-1.16.0\n"]},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["dateutil","six"]},"id":"9f14a9bdf04b419a9b17dd5b74149ba0"}},"metadata":{}},{"output_type":"stream","name":"stdout","text":["Collecting numpy==1.26.4\n","  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)\n","Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)\n","Installing collected packages: numpy\n","  Attempting uninstall: numpy\n","    Found existing installation: numpy 2.1.1\n","    Uninstalling numpy-2.1.1:\n","      Successfully uninstalled numpy-2.1.1\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","cudf-cu12 24.4.1 requires pandas<2.2.2dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.\n","mizani 0.11.4 requires pandas>=2.1.0, but you have pandas 1.5.3 which is incompatible.\n","plotnine 0.13.6 requires pandas<3.0.0,>=2.1.0, but you have pandas 1.5.3 which is incompatible.\n","xarray 2024.9.0 requires pandas>=2.1, but you have pandas 1.5.3 which is incompatible.\u001b[0m\u001b[31m\n","\u001b[0mSuccessfully installed numpy-1.26.4\n"]}]},{"cell_type":"code","execution_count":2,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"_LA3jEVMmFbX","executionInfo":{"status":"ok","timestamp":1726808456389,"user_tz":-540,"elapsed":22580,"user":{"displayName":"yuto “yuto2910” y","userId":"17489193892175419314"}},"outputId":"8146b0e6-d540-42ac-893a-b7cbbfda2d20"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive')"]},{"cell_type":"code","source":["import subprocess\n","\n","try:\n","    import japanize_matplotlib\n","    print(\"japanize_matplotlib is already installed.\")\n","except ImportError:\n","    !pip install japanize_matplotlib\n","    print(\"japanize_matplotlib has been installed.\")\n","\n","try:\n","    import catboost\n","    print(\"catboost is already installed.\")\n","except ImportError:\n","    !pip install catboost\n","    print(\"catboost has been installed.\")\n","\n","try:\n","    import optuna\n","    print(\"optuna is already installed.\")\n","except ImportError:\n","    !pip install optuna\n","    print(\"optuna has been installed.\")\n","\n","try:\n","    import geolib\n","    print(\"geolib is already installed.\")\n","except ImportError:\n","    !pip install geolib\n","    print(\"geolib has been installed.\")\n","\n","# mkdirとechoコマンドの実行\n","try:\n","    subprocess.check_call('mkdir -p /etc/OpenCL/vendors && echo \"libnvidia-opencl.so.1\" > /etc/OpenCL/vendors/nvidia.icd', shell=True)\n","    print('Directory and file for OpenCL vendors have been created.')\n","except subprocess.CalledProcessError as e:\n","    print(f\"Error running mkdir and echo command: {e}\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"34WC4UhZnSg5","executionInfo":{"status":"ok","timestamp":1726808487671,"user_tz":-540,"elapsed":31285,"user":{"displayName":"yuto “yuto2910” y","userId":"17489193892175419314"}},"outputId":"c4dc52d6-ee53-4e9c-adc6-9bc58a3a52c7"},"execution_count":3,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting japanize_matplotlib\n","  Downloading japanize-matplotlib-1.1.3.tar.gz (4.1 MB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m4.1/4.1 MB\u001b[0m \u001b[31m36.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from japanize_matplotlib) (3.7.1)\n","Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->japanize_matplotlib) (1.3.0)\n","Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->japanize_matplotlib) (0.12.1)\n","Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->japanize_matplotlib) (4.53.1)\n","Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->japanize_matplotlib) (1.4.7)\n","Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib->japanize_matplotlib) (1.26.4)\n","Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->japanize_matplotlib) (24.1)\n","Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->japanize_matplotlib) (10.4.0)\n","Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->japanize_matplotlib) (3.1.4)\n","Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->japanize_matplotlib) (2.9.0.post0)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->japanize_matplotlib) (1.16.0)\n","Building wheels for collected packages: japanize_matplotlib\n","  Building wheel for japanize_matplotlib (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for japanize_matplotlib: filename=japanize_matplotlib-1.1.3-py3-none-any.whl size=4120257 sha256=f459ecefe4c658c70a9cf3615245ecb799400fb3d4696c198837a838e2af93bc\n","  Stored in directory: /root/.cache/pip/wheels/61/7a/6b/df1f79be9c59862525070e157e62b08eab8ece27c1b68fbb94\n","Successfully built japanize_matplotlib\n","Installing collected packages: japanize_matplotlib\n","Successfully installed japanize_matplotlib-1.1.3\n","japanize_matplotlib has been installed.\n","Collecting catboost\n","  Downloading catboost-1.2.7-cp310-cp310-manylinux2014_x86_64.whl.metadata (1.2 kB)\n","Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.3)\n","Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)\n","Requirement already satisfied: numpy<2.0,>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.26.4)\n","Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.5.3)\n","Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.13.1)\n","Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.15.0)\n","Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)\n","Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)\n","Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2024.2)\n","Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.3.0)\n","Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.12.1)\n","Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.53.1)\n","Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.7)\n","Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (24.1)\n","Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (10.4.0)\n","Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.1.4)\n","Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (9.0.0)\n","Downloading catboost-1.2.7-cp310-cp310-manylinux2014_x86_64.whl (98.7 MB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m98.7/98.7 MB\u001b[0m \u001b[31m8.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hInstalling collected packages: catboost\n","Successfully installed catboost-1.2.7\n","catboost has been installed.\n","Collecting optuna\n","  Downloading optuna-4.0.0-py3-none-any.whl.metadata (16 kB)\n","Collecting alembic>=1.5.0 (from optuna)\n","  Downloading alembic-1.13.2-py3-none-any.whl.metadata (7.4 kB)\n","Collecting colorlog (from optuna)\n","  Downloading colorlog-6.8.2-py3-none-any.whl.metadata (10 kB)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from optuna) (1.26.4)\n","Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (24.1)\n","Requirement already satisfied: sqlalchemy>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (2.0.35)\n","Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from optuna) (4.66.5)\n","Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from optuna) (6.0.2)\n","Collecting Mako (from alembic>=1.5.0->optuna)\n","  Downloading Mako-1.3.5-py3-none-any.whl.metadata (2.9 kB)\n","Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna) (4.12.2)\n","Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=1.3.0->optuna) (3.1.0)\n","Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from Mako->alembic>=1.5.0->optuna) (2.1.5)\n","Downloading optuna-4.0.0-py3-none-any.whl (362 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m362.8/362.8 kB\u001b[0m \u001b[31m10.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading alembic-1.13.2-py3-none-any.whl (232 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m233.0/233.0 kB\u001b[0m \u001b[31m18.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading colorlog-6.8.2-py3-none-any.whl (11 kB)\n","Downloading Mako-1.3.5-py3-none-any.whl (78 kB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m78.6/78.6 kB\u001b[0m \u001b[31m7.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hInstalling collected packages: Mako, colorlog, alembic, optuna\n","Successfully installed Mako-1.3.5 alembic-1.13.2 colorlog-6.8.2 optuna-4.0.0\n","optuna has been installed.\n","Collecting geolib\n","  Downloading geolib-1.0.7-py3-none-any.whl.metadata (2.7 kB)\n","Requirement already satisfied: future in /usr/local/lib/python3.10/dist-packages (from geolib) (1.0.0)\n","Downloading geolib-1.0.7-py3-none-any.whl (5.5 kB)\n","Installing collected packages: geolib\n","Successfully installed geolib-1.0.7\n","geolib has been installed.\n","Directory and file for OpenCL vendors have been created.\n"]}]},{"cell_type":"code","source":["import pandas as pd\n","import numpy as np\n","import matplotlib.pyplot as plt\n","#import japanize_matplotlib\n","import seaborn as sns\n","import pickle\n","from catboost import CatBoostRegressor, Pool\n","import os\n","\n","import sys\n","sys.path.append('/content/drive/MyDrive/yuto/project_directory/code')\n","\n","from utils import (\n","                   to_cat_col,\n","                   VotingModel,\n","                   check_dataframe_elements\n","                   )\n","\n","TOTAL_PRICE_LOG=\"取引価格（総額）_log\"\n","PRICE_PER_AREA_LOG=\"単位面積あたりの取引価格_log\"\n","\n","sarima_model_path=\"/content/drive/MyDrive/yuto/project_directory/models/model_sarimax.pkl\""],"metadata":{"id":"IiH3nZQPmqsU","executionInfo":{"status":"ok","timestamp":1726808496736,"user_tz":-540,"elapsed":9074,"user":{"displayName":"yuto “yuto2910” y","userId":"17489193892175419314"}}},"execution_count":4,"outputs":[]},{"cell_type":"code","source":["df=pd.read_csv(\"/content/drive/MyDrive/yuto/project_directory/data/intermediate_results/checkpoints/preprocess_main_table.csv\",index_col=0)\n","df=df[['dataset', 'ID', '価格情報区分', '都道府県名', '市区町村名', '地区名', '住所不一致_Flag', '住所',\n","       '最寄駅：名称', '最寄駅：距離（分）', '徒歩時間_10分単位', 'x_api', 'y_api', 'lon', 'lat',\n","       '間取り', '面積（㎡）', '建築年', '建物の構造', '用途', '今後の利用目的', '都市計画', '建ぺい率（％）',\n","       '容積率（％）', '取引時点', '改装', '取引の事情等', '単位面積あたりの取引価格_log', '建築西暦年', '築年数',\n","       'log_面積（㎡）', '購入までの築年数', '面積（㎡）-最寄駅：距離（分）', '面積（㎡）-築年数',\n","       '面積（㎡）容積率（％）_combi', '旧耐震フラグ', '最寄駅までの距離', 'geohash_2', 'geohash_3',\n","       'geohash_4', 'geohash_5', 'geohash_6', 'geohash_7', '県_市_count',\n","       '建築年_count', '県_市_geohash_2_駅数', '県_市_geohash_3_駅数', '県_市_geohash_4_駅数',\n","       '県_市_geohash_5_駅数', '県_市_geohash_6_駅数', '県_市_geohash_7_駅数',\n","       '県_市_geohash_2_駅徒歩時間平均', '県_市_geohash_2_建築年平均', '県_市_geohash_3_駅徒歩時間平均',\n","       '県_市_geohash_3_建築年平均', '県_市_geohash_4_駅徒歩時間平均', '県_市_geohash_4_建築年平均',\n","       '県_市_geohash_5_駅徒歩時間平均', '県_市_geohash_5_建築年平均', '県_市_geohash_6_駅徒歩時間平均',\n","       '県_市_geohash_6_建築年平均', '県_市_geohash_7_駅徒歩時間平均', '県_市_geohash_7_建築年平均']]"],"metadata":{"id":"G9TRwJsFnc7k","executionInfo":{"status":"ok","timestamp":1726808531025,"user_tz":-540,"elapsed":34298,"user":{"displayName":"yuto “yuto2910” y","userId":"17489193892175419314"}}},"execution_count":5,"outputs":[]},{"cell_type":"code","source":["df_all_year=df.groupby(\"取引時点\")[f\"{PRICE_PER_AREA_LOG}\"].mean().rename(f\"{PRICE_PER_AREA_LOG}_mean\")\n","# 最後のインデックスに続けて新しい値を追加\n","last_index = df_all_year.index[-1]  # 最後のインデックスを取得\n","print(df_all_year.index)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"UO6gBagdnqEx","executionInfo":{"status":"ok","timestamp":1726808531025,"user_tz":-540,"elapsed":4,"user":{"displayName":"yuto “yuto2910” y","userId":"17489193892175419314"}},"outputId":"184ec0d2-f984-4cfb-b42c-206cb11055bd"},"execution_count":6,"outputs":[{"output_type":"stream","name":"stdout","text":["Float64Index([2005.75, 2005.99, 2006.25,  2006.5, 2006.75, 2006.99, 2007.25,\n","               2007.5, 2007.75, 2007.99, 2008.25,  2008.5, 2008.75, 2008.99,\n","              2009.25,  2009.5, 2009.75, 2009.99, 2010.25,  2010.5, 2010.75,\n","              2010.99, 2011.25,  2011.5, 2011.75, 2011.99, 2012.25,  2012.5,\n","              2012.75, 2012.99, 2013.25,  2013.5, 2013.75, 2013.99, 2014.25,\n","               2014.5, 2014.75, 2014.99, 2015.25,  2015.5, 2015.75, 2015.99,\n","              2016.25,  2016.5, 2016.75, 2016.99, 2017.25,  2017.5, 2017.75,\n","              2017.99, 2018.25,  2018.5, 2018.75, 2018.99, 2019.25,  2019.5,\n","              2019.75, 2019.99, 2020.25,  2020.5, 2020.75, 2020.99, 2021.25,\n","               2021.5, 2021.75, 2021.99, 2022.25,  2022.5, 2022.75, 2022.99,\n","              2023.25,  2023.5, 2023.75, 2023.99],\n","             dtype='float64', name='取引時点')\n"]}]},{"cell_type":"code","source":["# モデルの読み込み\n","#model_path = r\"C:\\Users\\yuto2\\OneDrive\\ドキュメント\\Pythonフォルダ\\Nishika\\中古マンション価格予測_2024夏の部\\Nishika1st_動けばOK\\model_sarimax.pkl\"\n","# Pandasのバージョンを確認\n","print(pd.__version__)\n","\n","# Pandasのバージョンが2.0以降の場合、以下を試してください。\n","try:\n","    with open(sarima_model_path, 'rb') as file:\n","        SARIMA_model_fit = pickle.load(file)\n","except ModuleNotFoundError:\n","    # Pandas 1.5.3を強制的に再インストール\n","    !pip install --force-reinstall pandas==1.5.3\n","    !pip install --force-reinstall numpy==1.26.4\n","    # Pandasをインポートし直す\n","    import pandas as pd\n","    with open(sarima_model_path, 'rb') as file:\n","        SARIMA_model_fit = pickle.load(file)\n","\n","\n","print(\"モデルの読み込みが完了しました。\")\n","\n","# 予測の実行\n","SARIMA_pred = SARIMA_model_fit.get_forecast(steps=2)\n","SARIMA_pred_df = SARIMA_pred.summary_frame()\n","\n","# 予測結果の表示\n","print(SARIMA_pred_df)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"47yuBvk0uNmO","executionInfo":{"status":"ok","timestamp":1726808531653,"user_tz":-540,"elapsed":631,"user":{"displayName":"yuto “yuto2910” y","userId":"17489193892175419314"}},"outputId":"630a1253-1f26-4edf-d0c9-9592ec39baf7"},"execution_count":7,"outputs":[{"output_type":"stream","name":"stdout","text":["1.5.3\n","モデルの読み込みが完了しました。\n","単位面積あたりの取引価格_log_mean      mean   mean_se  mean_ci_lower  mean_ci_upper\n","72                     5.629596  0.014408       5.601356       5.657837\n","73                     5.634549  0.019483       5.596363       5.672735\n"]},{"output_type":"stream","name":"stderr","text":["/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n","  return get_prediction_index(\n"]}]},{"cell_type":"code","source":["#print(df_all_year)\n","df_all_year.loc[2023.75]=SARIMA_pred_df[\"mean\"][72]\n","df_all_year.loc[2023.99]=SARIMA_pred_df[\"mean\"][73]\n","print(df_all_year)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"KmMy_YULA2II","executionInfo":{"status":"ok","timestamp":1726811979119,"user_tz":-540,"elapsed":473,"user":{"displayName":"yuto “yuto2910” y","userId":"17489193892175419314"}},"outputId":"9f1cc3f6-10bf-4ce7-df61-33e68f5d7bd1"},"execution_count":8,"outputs":[{"output_type":"stream","name":"stdout","text":["取引時点\n","2005.75    5.603129\n","2005.99    5.600274\n","2006.25    5.610975\n","2006.50    5.505956\n","2006.75    5.511552\n","             ...   \n","2022.99    5.617195\n","2023.25    5.624689\n","2023.50    5.620718\n","2023.75    5.629596\n","2023.99    5.634549\n","Name: 単位面積あたりの取引価格_log_mean, Length: 74, dtype: float64\n"]}]}]}